Introduce adventure boss
planetarium/NineChronicles.DataProvider pull request #705
Opened 2024-07-01 05:59 UTC by U-lis

Saving adventure boss data to DataProvider

2024-07-01 09:52 UTC, ipdae requested changes

2024-07-01 09:52 UTC, ipdae commented on NineChronicles.DataProvider/DataRendering/AdventureBoss/AdventureBossClaimRewardData.cs
> +                NcgReward = (decimal)(myReward.NcgReward?.RawValue / 100 ?? 0),
getQuantityString을 쓰시면 문자열로 처리된 decimal값을 가져올수있습니다. https://github.com/planetarium/NineChronicles.DataProvider/blob/development/NineChronicles.DataProvider/DataRendering/TransferAssetData.cs#L32

2024-07-01 09:52 UTC, ipdae commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
> +                foreach (var season in seasonList)
다른 메서드들도 전부 루프를 돌때마다 컨텍스트를 만들고 있는데, 그래야할 이유가 있나요? 컨텍스트 관리는 메서드 시작과 끝에서 한번씩만 처리하면 될것같습니다.

2024-07-01 09:52 UTC, ipdae commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
> +                        if (ctx.AdventureBossSeason.FindAsync(season.Season).Result is null)
보니까 시즌을 돌면서 upsert를 하는 구조같은데, 대상 시즌 아이디들을 기준으로 쿼리해오고 없는 케이스만 insert하게 해주면 될것같습니다.

2024-07-02 01:21 UTC, area363 commented
@U-lis Could you rebase this branch to development? 🙏

2024-07-02 02:26 UTC, U-lis commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
> +                foreach (var season in seasonList)
`new List<Task>` 말씀하시는거죠?  이게 따로 불려서 따로 관리한다고 생각했는데 한번에 할 수 있나 함 보겠습니다.

2024-07-02 02:28 UTC, U-lis commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
> +                        if (ctx.AdventureBossSeason.FindAsync(season.Season).Result is null)
season 정보는 만들어질때 한번 생성되고, 첫 claim 을 할 때 한번 업데이트됩니다 (random 보상 뽑기) 그래서 Wanted action 안에서 insert 를 하고, claim action 안에서 update를 해야 해서 upsert 를 넣어두었습니다.

2024-07-02 14:33 UTC, ipdae requested changes
경험상 RenderSubscriber는 직접 돌려서 들어가나 확인해보는 수밖에 없었던것같긴한데, MySqlStore 입장에서 각 메서드별로 list를 넣었을때 동작이 의도대로 동작하는(Upsert가 제대로 되는지) 확인하는 유닛테스트는 추가해놔야할것같습니다.

2024-07-02 14:33 UTC, ipdae commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
>                              await ctx.AdventureBossSeason.AddRangeAsync(season);
season 의 타입은 `AdventureBossModel` 인것같은데 이경우엔 AddRange가 아니라 Add로 처리해야할것같습니다.

2024-07-02 14:33 UTC, ipdae commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
> +                            ctx.AdventureBossSeason.UpdateRange(season);
이쪽도 Range대신 그냥 Update를 불러야할 것 같네요.

2024-07-02 14:33 UTC, ipdae commented on NineChronicles.DataProvider/Store/MySql/AdventureBossStore.cs
> +                        if (ctx.AdventureBossSeason.FindAsync(season.Season).Result is null)
`await FirstOrDefaultAsync`를 쓰면 .Result로 기다릴필요가 없을것 같습니다.

2024-07-03 11:31 UTC, ipdae approved these changes

2024-07-03 12:31 UTC, merged